###
post http://localhost:3000/login/admin
Content-Type: application/json

{
    "username":"amir",
    "password":"12345678"
}

//Admin

###
post http://localhost:3000/create/user
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDMzMTYwOTAsImV4cCI6MTcwMzMxNjY5MH0.EpMukcGT7bHe80I0-vbdpBiWr-LCyPhCGyT5WGgT6lI
Content-Type: application/json

{
    "username":"Siti",
    "idproof":"b022120004"

} 

###
GET http://localhost:3000/view/user/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MDQyNzEsImV4cCI6MTcwMzQwNDg3MX0.h6HO3lrp1jKXdACLuB3wqs3-9S5NjLbAhs9Z8Svrmbc

//Visitor

###
post http://localhost:3000/create/visitor
Content-Type: application/json

{
    "visitorname": "Dr Aisyah",
    "idproof": "d123",
    "entrytime":1045
}

###
GET http://localhost:3000/view/visitor/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MDQyNzEsImV4cCI6MTcwMzQwNDg3MX0.h6HO3lrp1jKXdACLuB3wqs3-9S5NjLbAhs9Z8Svrmbc
//Visitor log


###
DELETE http://localhost:3000/delete/visitor/5678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MDgwMjUsImV4cCI6MTcwMzQwODYyNX0.RSlLQg__4m9HF9DyRZ8oGdweTKiEte-QbnSa6YECXA8
Content-Type: application/json

{
    "idproof": "5678"
}


###
post http://localhost:3000/create/visitorlog/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MDQyNzEsImV4cCI6MTcwMzQwNDg3MX0.h6HO3lrp1jKXdACLuB3wqs3-9S5NjLbAhs9Z8Svrmbc
Content-Type: application/json

{
    "visitorname": "dr khoo",
    "idproof": "d123",
    "timespend": 3,
    "payment": 12
}

###
GET http://localhost:3000/view/visitorlog/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MDQ3NTYsImV4cCI6MTcwMzQwNTM1Nn0.jl2KtsfGHSG4MnL54WOCqCYvCo8MjSz8yw0YIjfmd9w
Content-Type: application/json


###
POST http://localhost:3000/create/computer
Content-Type: application/json

{
    "idproof": "b0123", 
    "lanportno": 31738124,
    "available": "yes"
}

###
GET http://localhost:3000/view/computer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MDQ3NTYsImV4cCI6MTcwMzQwNTM1Nn0.jl2KtsfGHSG4MnL54WOCqCYvCo8MjSz8yw0YIjfmd9w