GET http://localhost:3002/view/customer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODcwOTc0NzIsImV4cCI6MTY4NzA5ODA3Mn0.w94oPntPJDKHjdYR1u9EHNx62hunHhh5XpDLwygI1xs

###
post http://localhost:3002/create/customer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODcwNzY0MDUsImV4cCI6MTY4NzA3NjQ2NX0.htt2LYWbyyEMcFg4Cz9N7jJjss7QbpTlBEf-F5upAYo
Content-Type: application/json

{
    "customername":"Afifi",
    "idproof":"b022120017"

}
###
post http://localhost:3002/login/admin
Content-Type: application/json

{
    "username":"amir",
    "password":"12345678"
}

###
PUT http://localhost:3002/update/customer/b022120017
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODcwNzY1MjIsImV4cCI6MTY4NzA3NjU4Mn0.MYAb3btYgRkEzljryW3Fs1DWvBc5TPJsxQMorkYdMcI
Content-Type: application/json

{
    "cabinno": 1,
    "entrytime": 1230,
    "payment": 9,
    "timespend": 3
}
###
POST http://localhost:3002/create/computer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODcwOTM3MzQsImV4cCI6MTY4NzA5Mzc5NH0.H3RXXxEdmhM_kZW3h7aBej2TNi9WqHucHcJifaS5PXM
Content-Type: application/json

{
    "computername": "system 1",
    "cabinno": 1,
    "lanportno": 129076927,
    "systemworking": "working", 
    "available": "no"

}
###
PUT http://localhost:3002/update/computer/system 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODcwOTYwNTAsImV4cCI6MTY4NzA5NjExMH0.72vQ-x9cVvkflV8dxWc9XsA80OAFbBobUVGPH4vPqdw
Content-Type: application/json

{
    "lanportno": 129076927,
    "systemworking": "not working",
    "available": "yes"
}
###
DELETE http://localhost:3002/delete/customer/b022120017
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODcwNzY1MjIsImV4cCI6MTY4NzA3NjU4Mn0.MYAb3btYgRkEzljryW3Fs1DWvBc5TPJsxQMorkYdMcI
Content-Type: application/json

{
    "idproof": "b022120017"
}

###
DELETE http://localhost:3002/delete/computer/system 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE2ODcwOTY0MzEsImV4cCI6MTY4NzA5NzAzMX0.BkE1o4h8ViXirn2TKmWqybW6yMSRvHHqoFgupeBbHng
Content-Type: application/json

{
    "computername": "system 1"
}

###
DELETE http://localhost:3002/logout